### PR TITLE
Adding a Cloudinary backend

### PR DESCRIPTION
**Pull request by yuval-cloudinary**
#### What is the purpose of this change?
Adding a backend for the popular service [Cloudinary](https://cloudinary.com/)

#### Was the change discussed in an issue or in the forum before?
https://github.com/rclone/rclone/issues/7989

#### Checklist

- [v]I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [v] I have added tests for all changes in this PR if appropriate.
- [v] I have added documentation for the changes if appropriate.
- [v] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [v] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by dhuf** [comment]
Hi @yuval-cloudinary, I just tried your pull-request and I get this error:

```
docker run --rm --volume ./config/rclone:/config/rclone --volume ./data:/data:shared  --user $(id -u):$(id -g) myrclone/rclone:cloudinary lsd Cloudinary-dev:
```

```
ERROR : : error listing: failed to list assets: invalid character '<' looking for beginning of value
2024/08/27 08:45:12 Failed to lsd with 2 errors: last error was: failed to list assets: invalid character '<' looking for beginning of value
```

Do you know what it could be ? Thanks

**Comment by yuval-cloudinary** [comment]
@dhuf I'm about to submit significant encoding changes. Probably next week. I'll mention you when ready, and will also test your example. Thanks!

**Comment by yuval-cloudinary** [comment]
@dhuf I've completed full testing and revised encodings, also submitted https://github.com/rclone/rclone/pull/8051
Here is an example of `lsd` which you referred to earlier:
```shell
% rclone lsd TestCloudinary:                                                                                                                                   
          -1 2000-01-01 02:00:00        -1 Folder%202
          -1 2000-01-01 02:00:00        -1 Folder1
```

The character `<` is not a valid character in Cloudinary, so I cannot show you such a result

You can share with me your Cloudinary environment name and the permission to access it as a Cloudinary employee, and I'd be able to test it on your environment

**Comment by yuval-cloudinary** [comment]
merging

**Comment by dhuf** [comment]
Thanks @yuval-cloudinary I'll have a try

**Comment by dhuf** [comment]
I still have the same error, I'll try with another Driver to see what is going on

**Pull request closed without merging**
